/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.toddy.msnclientgui.windows;

import com.toddy.msnclientgui.Main;
import com.toddy.msnclientgui.enums.ResponseStatus;
import com.toddy.msnclientgui.network.NetworkUtils;
import com.toddy.msnclientgui.utils.Utils;
import com.toddy.msnclientgui.views.JCustomButton;
import com.toddy.msnclientgui.views.RoundedBorder;
import com.toddy.msnclientgui.views.UI.JPasswordFieldHintUI;
import com.toddy.msnclientgui.views.UI.JTextFieldHintUI;
import java.awt.Color;
import java.awt.Image;
import java.awt.Rectangle;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.json.JSONObject;

public class SignUp extends javax.swing.JFrame
{

    private JFrame parentWindow;
    
    public SignUp(JFrame parentWindow)
    {
	this.parentWindow = parentWindow;
	this.addWindowListener(new WindowAdapter()
	{
	    @Override
	    public void windowClosing(WindowEvent event)
	    {
		parentWindow.setEnabled(true);
	    }
	});
	initComponents();
	Title.requestFocus();
	this.setLocationRelativeTo(parentWindow);
	try
	{
	    setIconImage(Utils.getAppIcon());
	} 
	catch (IOException ex)
	{
	    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
	}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        Outter = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        UserNameField = new javax.swing.JTextField();
        UserNameLabel = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        EmailField = new javax.swing.JTextField();
        PasswordLabel = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        SignUpButton = new com.toddy.msnclientgui.views.JCustomButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sign up");
        setBackground(new java.awt.Color(252, 252, 252));
        setResizable(false);

        try
        {
            BufferedImage backgroundToCrop = ImageIO.read(getClass().getClassLoader().getResource("com/toddy/msnclientgui/resources/images/default-messenger-wide.jpg"));
            Rectangle rect = new Rectangle(600, 110);
            Image backgroundCropped = backgroundToCrop.getSubimage(300, 0, rect.width, rect.height);
            Outter = new com.toddy.msnclientgui.views.JImage(backgroundCropped);
            //UserProfilePicture.setIcon(new ImageIcon(userProfilePicResized));
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
        Outter.setBackground(new java.awt.Color(252, 252, 252));
        Outter.setPreferredSize(new java.awt.Dimension(210, 300));
        Outter.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setBackground(new java.awt.Color(252, 252, 252));
        Title.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Title.setForeground(new java.awt.Color(0, 0, 0));
        Title.setText("Sign Up");
        Outter.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 28, -1, -1));

        UserNameField.setUI(new JTextFieldHintUI("Anne Campbell", Color.gray));
        UserNameField.setBorder(new RoundedBorder(new Color(171,187,208), 1, UserNameField.getInsets()));
        UserNameField.setForeground(new java.awt.Color(0, 0, 0));
        UserNameField.setPreferredSize(new java.awt.Dimension(170, 24));
        Outter.add(UserNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 85, 180, -1));

        UserNameLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        UserNameLabel.setForeground(new java.awt.Color(0, 0, 0));
        UserNameLabel.setText("Your Name:");
        UserNameLabel.setPreferredSize(new java.awt.Dimension(60, 14));
        Outter.add(UserNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 68, 76, -1));

        EmailLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        EmailLabel.setForeground(new java.awt.Color(0, 0, 0));
        EmailLabel.setText("Email:");
        EmailLabel.setPreferredSize(new java.awt.Dimension(60, 14));
        Outter.add(EmailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 115, 76, -1));

        EmailField.setUI(new JTextFieldHintUI("example555@mesquita.com.br", Color.gray));
        EmailField.setBorder(new RoundedBorder(new Color(171,187,208), 1, UserNameField.getInsets()));
        EmailField.setForeground(new java.awt.Color(0, 0, 0));
        EmailField.setPreferredSize(new java.awt.Dimension(170, 24));
        Outter.add(EmailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 132, 180, -1));

        PasswordLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        PasswordLabel.setForeground(new java.awt.Color(0, 0, 0));
        PasswordLabel.setText("Password:");
        PasswordLabel.setPreferredSize(new java.awt.Dimension(60, 14));
        Outter.add(PasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 162, 76, -1));

        PasswordField.setMinimumSize(new java.awt.Dimension(170, 24));
        PasswordField.setUI(new JPasswordFieldHintUI("Password", Color.gray));
        PasswordField.setBorder(new RoundedBorder(new Color(171,187,208), 1, UserNameField.getInsets()));
        Outter.add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 182, 180, 24));

        SignUpButton.setBackground(new java.awt.Color(252, 252, 252));
        SignUpButton.setForeground(new java.awt.Color(0, 0, 0));
        SignUpButton.setText("Sign Up");
        SignUpButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        SignUpButton.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                SignUpButtonMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                SignUpButtonMouseExited(evt);
            }
        });
        Outter.add(SignUpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 218, -1, 21));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Outter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Outter, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SignUpButtonMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_SignUpButtonMouseExited
    {//GEN-HEADEREND:event_SignUpButtonMouseExited
        SignUpButton.mouseExit();
    }//GEN-LAST:event_SignUpButtonMouseExited

    private void SignUpButtonMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_SignUpButtonMouseClicked
    {//GEN-HEADEREND:event_SignUpButtonMouseClicked
        String pass = new String(PasswordField.getPassword());
	boolean isEmailOk = Utils.isValidEmailAddress(EmailField.getText());
	boolean isPassOk = (pass != null && !pass.isEmpty());
	boolean isUsernameOk = (UserNameField.getText() != null && !UserNameField.getText().isEmpty());
	if(isEmailOk && isPassOk && isUsernameOk)
	{
	    EmailField.setBorder(new RoundedBorder(new Color(171,187,208), 1, EmailField.getInsets()));
	    PasswordField.setBorder(new RoundedBorder(new Color(171,187,208), 1, PasswordField.getInsets()));
	    UserNameField.setBorder(new RoundedBorder(new Color(171,187,208), 1, UserNameField.getInsets()));
	    
	    try
	    {
		NetworkUtils.connect();
		JSONObject response = NetworkUtils.signup(UserNameField.getText(), EmailField.getText(), pass);
		NetworkUtils.disconnect();
		if(response.getEnum(ResponseStatus.class, "Status") == ResponseStatus.Authorized)
		{
		    JOptionPane.showMessageDialog(this, "You are now signed up. Please, log in!",  "Live Messenger", JOptionPane.INFORMATION_MESSAGE);
		    dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
		}
		else if(response.getEnum(ResponseStatus.class, "Status") == ResponseStatus.InternalError)
		{
		    throw new Exception("Internal error");
		}
		else
		{
		    JOptionPane.showMessageDialog(this, "Email already registered!",  "Live Messenger", JOptionPane.WARNING_MESSAGE);
		}
	    } 
	    catch (Exception ex)
	    {
		JOptionPane.showMessageDialog(this, "An error has occurred while you were trying to sign up\nError Code: 003",  "Live Messenger", JOptionPane.ERROR_MESSAGE);
		Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
	    }
	}
	else
	{
	    if(!isEmailOk)
	    {
		EmailField.setBorder(new RoundedBorder(Color.RED, 1, EmailField.getInsets()));
	    }
	    else
	    {
		EmailField.setBorder(new RoundedBorder(new Color(171,187,208), 1, EmailField.getInsets()));
	    }
	    
	    if(!isPassOk)
	    {
		PasswordField.setBorder(new RoundedBorder(Color.RED, 1, PasswordField.getInsets()));
	    }
	    else
	    {
		PasswordField.setBorder(new RoundedBorder(new Color(171,187,208), 1, PasswordField.getInsets()));
	    }
	    
	    if(!isUsernameOk)
	    {
		UserNameField.setBorder(new RoundedBorder(Color.RED, 1, UserNameField.getInsets()));
	    }
	    else
	    {
		UserNameField.setBorder(new RoundedBorder(new Color(171,187,208), 1, UserNameField.getInsets()));
	    }
	}
    }//GEN-LAST:event_SignUpButtonMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EmailField;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JPanel Outter;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel PasswordLabel;
    private com.toddy.msnclientgui.views.JCustomButton SignUpButton;
    private javax.swing.JLabel Title;
    private javax.swing.JTextField UserNameField;
    private javax.swing.JLabel UserNameLabel;
    // End of variables declaration//GEN-END:variables
}
